### ISSUE TITLE
buildtest settings update

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#303]
@vsoch i am trying to work on another revision for buildtest settings file, here is an overview of some of the changes, i wanted to propose and would like your input. I will work on the schema in the meantime but figured i shared this now since changes to YAML will require changes to json schema.

![Screen Shot 2020-05-26 at 9 03 38 PM](https://user-images.githubusercontent.com/12942230/82964863-885d1800-9f94-11ea-843c-9018786075a2.png)

The `printenv` section is an executor specific configuration that allows all tests using the given executor to have environment variables injected into job script. The printenv is just going to echo the environment variable as simple as `echo $FOO`

The `config` section is where the core of buildtest configuration is setup, so this where you can configure `tests` `slurm` `paths` and `vars` which are configuration sections somehow related to buildtest. For instance `tests`  can have a timeout in seconds, if test fails to complete in given time this would be marked as fail. The `paths` where we define buildtest configuration, if it's not defined buildtest will resort to default behavior what we have. Setting these paths would be nice to have full control where user wants to store files depending on the filesystem preference (paralllel file-system, scratch, home, etc...)

The `vars` section is used to define any global variables accessible by all tests, the idea is to have a location to define a shared variable and this will be sourced into script or automatically added into script. 

Each of the global configuration in `config` could be overridden if defined in `executors` section which would be associated to a particular test.

The `slurm` section is where we define slurm configuration shared by all slurm executor, at the moment, i know i will have to poll a slurm job via `sacct` to periodically check if job has finished before buildtest reports test is complete. I can remove this for now and maybe implement this when i get slurm executor working. It is on my TODO list asap.

What do you think of this setup?

**Comment by vsoch** [comment]
I think instead of needing to define another set of variables for the settings file, it would make sense to have a rule that any already existing keys that are defined there for an executor can be passed to the executor, either by replacement or extension.  That way you don't have to re-design another schema, you have a method to write settings for any schema. For validation you would use some section of the settings for the executor to update it, and _then_ validate it.

As for `printenv` specifically, it's not super intuitive what that means. It would be more clear to just have it be `env`, and again to have that as a known class attribute for the executor that can be extended. 

If executors have a similar ability to define variables under config - I would do something similar. There should be a standard way an executor knows how to look for and update any things relevant to it's configuration. 

Let's start with that and think about the other sections (vars, paths, test settings) later. Generally I'd say it makes sense to have other config settings that can be put here, and for each, it should be possible to override them on the command line. For example for [qme](https://vsoch.github.io/qme/getting-started/configure/index.html#sqlite) you can update your config with something like:

```
qme config --database <database>
```

**Comment by shahzebsiddiqui** [comment]
For now i have only defined `paths` and just keep a mental note to add other sections as needed. The `paths` section is integrated into framework but more testing is needed. I will add the equivalent schema change in `schema` repo very soon.
